name: Terraform EC2 Deploy

on:
  push:
    paths:
      - 'ec2-instance-basic/**'

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ec2-instance-basic

      - name: Terraform Plan
        run: terraform plan
        working-directory: ec2-instance-basic

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ec2-instance-basic
